### ISSUE TITLE
Need an code for super market using tkinter in python GUI ... can help me in this 

### ISSUE THREAD

**Issue by Kaushal03** [geekcomputers/Python#1250]

**Comment by mearchit** [comment]
Sir I can work on this ,if you provide me the opportunity!

**Comment by yashzod** [comment]
Yes. I already have a similar code.

**Comment by Kaushal03** [comment]
> Sir I can work on this ,if you provide me the opportunity!

ok u can try if u can get me the code for it ....

**Comment by Kaushal03** [comment]
> Yes. I already have a similar code.

ok then can u send me the code

**Comment by yashzod** [comment]
> > Yes. I already have a similar code.
> 
> ok then can u send me the code

assign me the issue I'll try to complete asap.

**Comment by mearchit** [comment]
I can work on this uf you provide me the brief idea about your project !
