### ISSUE TITLE
pytest ```test_case.py```

### ISSUE THREAD

**Issue by slowy07** [geekcomputers/Python#1352]
hello, i have problem with pytestest on github check, on ```Test-Case-Generator/test_case.py``` have problem on pytest github action with error

```
Test-Case-Generator/test_case.py:13: in <module>
    gui = Tk()
/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/tkinter/__init__.py:2270: in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
E   _tkinter.TclError: no display name and no $DISPLAY environment variable
```
so, pytest (github action pytest) n't support test for tkinter (GUI) ??, and i works and no error on local check with pytest 

so i created by adding 
```python
if os.environ.get('DISPLAY', '') == '':
    print('no display found, using:0,0')
    os.environ.__setitem__('DISPLAY', ':0.0')
```
and works on my local test but error  in github pytest and still same, any solution ??

thanks 😊

**Comment by shivamsp133** [comment]
REFER
https://github.com/microsoft/vscode-python/issues/15398
