### ISSUE TITLE
List

### ISSUE THREAD

**Issue by Mahi8585** [geekcomputers/Python#1457]
Hello , if I wanna know to wich member of my list have a number in its 3rd home ?
For example I have list such as this:
[[[1,1,1,-1]
   [2,3,4,6]
   [1,1,-1,2]
   [1,1,1,3]]]
 and  I need to know wich of them has number -1 in its third home 
and it should show me the list number 3 
[1,1,**-1**,2] 
Could you please help me

**Comment by BeASTBLASTER** [comment]
n=[[1,1,1,-1],[2,3,4,6],[1,1,-1,2],[1,1,1,3]]
for i in n:
    if i[-2]==-1:
        print(i)
As you can see it is the nested list so basically we come out of inside list to inside list to check the element from the last 2 which is third from start . It will print in final contion

**Comment by Mahi8585** [comment]
Thank you 🌺

**Comment by danielribeiro53744** [comment]
n = [[1, 1, 1, -1], [2, 3, 4, 6], [1, 1, -1, 2], [1, 1, 1, 3]]
x = list(filter(lambda x: x[2] == -1, n))
print(x)
With this you get a list with all the objects(list) that have the condition inside the filter, if it doesn't exists it will return an empty list
