### ISSUE TITLE
Dictionaries 

### ISSUE THREAD

**Issue by implosion07** [geekcomputers/Python#1458]
Can anyone help me out with dictionaries in python via an illustrative code?

**Comment by darshang99** [comment]
#dictionaries are unordered collection key-value pairs.
#dictionaries syntax goes as below
dict = {
  'key' : 'value' ,
  'key2' : 'value2'
}
#like if u want an example

dict = {
  'name' : 'darshan',
  'occupation' : 'student'
}

#so if you want to access the dictionary you can just use
print(dict['name'])
#output will be the value that is associated with the key name so you get(darshan)

#if you want all the keys present in the dictionary you can just say
print(dict.keys())

#same goes with the values just say
print(dict.values())

#if you want to access both key-value then just say
print(dict.items())

#thank you
