### ISSUE TITLE
Does any functions can be used to replace cv2.imwrite?

### ISSUE THREAD

**Issue by hhwhbf** [geekcomputers/Python#155]
Hi,I use python3 to test a model which need opencv(CV2),but I failed to install opencv on windows.
Therefore,I try to find a functions which belongs to numpy or PIL to replace it. 
Here are partial codes of the program.

 for rec_val, img,x,y in zip(reconstruction_vals, test_images, xs, ys):
                    rec_hid = (255. * (rec_val+1)/2.).astype(int)
                    rec_con = (255. * (img+1)/2.).astype(int)

                    rec_con[y:y+64, x:x+64] = rec_hid
                    cv2.imwrite( os.path.join(result_path, 'img_'+str(ii)+'.'+str(int(iters/100))+'.jpg'), rec_con)
                    ii += 1
                    if ii > 50: break

                if iters == 0:
                    ii = 0
                    for test_image in test_images_ori:
                        test_image = (255. * (test_image+1)/2.).astype(int)
                        test_image[32:32+64,32:32+64] = 0
                        cv2.imwrite( os.path.join(result_path, 'img_'+str(ii)+'.ori.jpg'), test_image)
                        ii += 1
                        if ii > 50: break

and the code can be find in https://github.com/jazzsaxmafia/Inpainting   /src/train.imagenet.py

**Comment by geekcomputers** [comment]
Feel free to add to the repo

Cheers
