### ISSUE TITLE
Better folder structure.

### ISSUE THREAD

**Issue by shreydan** [geekcomputers/Python#158]
This repo has a lot of great programs, it would be great if similar types of programs were organized into folders so it is easier to find them and would be better in the future for more programs to be added to this repo.

**Comment by ankit167** [comment]
I agree on this. There are scripts across various domains. An organized folder structure is needed.

**Comment by w666x** [comment]
I agree on this too.

**Comment by geekcomputers** [comment]
What do you propose?

**Comment by shreydan** [comment]
@geekcomputers Maybe arrange Python scripts on basis of modules used or type of programs. For eg: API, algorithms, Math, automation, web scraping, PiPy modules, Python's inbuilt modules, string manipulation, etc.

Of course some scripts can come under multiple categories but it also may depend on the purpose of the script.

That is how I organized mine: [shreydan/Python](https://github.com/shreydan/Python)
