### ISSUE TITLE
Changing a list while iterating over it may cause unpredictable result.

### ISSUE THREAD

**Issue by fanofxiaofeng** [geekcomputers/Python#200]
In check_file.py, the list `filenames` is changed on line 40 and line 47.
Thus, some items may skip the for loop (and does not get the existance check and read permission check), when you try to read such items on line 54, an error may be thrown.

For example, suppose there is non-readable file f1 and non-exist file f2 in current directory, and we execute the command `python check_file.py f1 f2`, we will see an error as shown in the picture.
![image](https://user-images.githubusercontent.com/3983683/28247458-6d237034-6a63-11e7-91b8-0f56cd9e0518.png)

**Comment by geekcomputers** [comment]
Please feel free to change it on the repo

**Comment by ArighnaIITG** [comment]
Is this issue closed?

**Comment by fanofxiaofeng** [comment]
I forgot to close it.
