### ISSUE TITLE
Create a function to extract thumbnail from a video file

### ISSUE THREAD

**Issue by ibtsam3301** [geekcomputers/Python#2026]
I would like to contribute by creating a function to extract thumbnail from a video file.
@NitkarshChourasia please assign me this issue

**Comment by NitkarshChourasia** [comment]
Now you can close this issue. @ibtsam3301

**Comment by NitkarshChourasia** [comment]
@ibtsam3301 Merging will be done by @geekcomputers when you complete the issues with the projects.
Thanks for contributing.
