### ISSUE TITLE
[not an issue] use requirement.txt for all depcies.

### ISSUE THREAD

**Issue by anuragkumarak95** [geekcomputers/Python#224]
hey,

really liked these codes. inspirational i must say... :100: ..

Why don't you create a .txt file and put all dependencies for using any of the codes in this source, might be helpful for all.

**Comment by geekcomputers** [comment]
Good idea, can you expand some more of what you mean dependencies?

**Comment by anuragkumarak95** [comment]
hey, 

What i meant was create a requirements.txt file with all required package's names and versions (pkg_name==v.v.v) to be used in these modules. 

when a new fellow coder will fork this project, he/she could just do 'pip install -r requirements.txt' at the root_dir, after which they will have all dependencies for every module in this project. 

I can make one for your project if you want, will be pleased to help out. :+1:
