### ISSUE TITLE
Comment it!

### ISSUE THREAD

**Issue by RGauthamRam** [geekcomputers/Python#227]
For ex20.py
Comment "What is the program and what will it do"

**Comment by yadneshk** [comment]
the code accepts a simple text file opens it
read() function will read the text in file
seek() will set the pointer to previous statements...which will execute some statements again
and finally it prints three lines of the text file

**Comment by RGauthamRam** [comment]
It will be better if you comment in thr program itself..

**Comment by tyshawngaines** [comment]
Looks s if pertains to text files. Personally I'd run it on my desktop app to find out the if's and whats.
