### ISSUE TITLE
ImportError: cannot import name IOBase?

### ISSUE THREAD

**Issue by zhoujinhai** [geekcomputers/Python#240]
I have get a problem when I run  test.py on pycharm, but the code can run success when use IDLE

error message:
```
Traceback (most recent call last):
  File "E:/python/test/database2.py", line 6, in <module>
    import mysql.connector
  File "C:\Python27\lib\site-packages\mysql\connector\__init__.py", line 37, in <module>
    from .connection import MySQLConnection
  File "C:\Python27\lib\site-packages\mysql\connector\connection.py", line 27, in <module>
    from io import IOBase
ImportError: cannot import name IOBase
```

test.py
```
import mysql.connector

conn = mysql.connector.connect(host='localhost', user='root', password='z2457098495924', database='test')

cur = conn.cursor()
cur.execute('select * from student')
result = cur.fetchall()
print result

conn.commit()
cur.close()
conn.close()
```
and my pycharm setting:
![image](https://user-images.githubusercontent.com/20365125/30999360-5d88ed3c-a507-11e7-83d1-14ba640a7da1.png)

**Comment by faresbessrour** [comment]
Can you try to reinstall with pip the io package with this command: 
```bash
pip install --upgrade --force-reinstall io
```

**Comment by zhoujinhai** [comment]
@faresbessrour sorry! I have try and show follow error:
![image](https://user-images.githubusercontent.com/20365125/31041017-7bea8f96-a5c1-11e7-89f5-4adc366430df.png)

**Comment by zhoujinhai** [comment]
thanks！it works . it can't run due to my fault that i create a file which named io.py
