### ISSUE TITLE
batch_file_rename doesn't do anything

### ISSUE THREAD

**Issue by jdhines** [geekcomputers/Python#27]
I'm learning python, and after having done some lessons, it was suggested that I browse Github, find a python project, and just read some code to gain more experience. Your batch file rename script is the first one I looked at, and it appears to have an error.

You have the following code:

`if old_ext == file_ext:`

which means it will only "rename" to the same name, defeating the purpose of the entire script.

**Comment by FelixDavidson** [comment]
Have you tried running the script because it works.

**Comment by bravesnail** [comment]
@jdhines exactly , it's used to modify extension.

**Comment by jdhines** [comment]
@bravesnail Ah, ok. I do see that now. I guess I was confused by the comments saying it would rename a batch of files, but didn't mention that it's purpose was just to rename extensions. My recent use cases for batch rename are renaming a bunch of images with generic names (like img001.jpg) to something else (like my_neat_event_20151231_1.jpg), so that was my frame of reference.

**Comment by bravesnail** [comment]
@jdhines i just rewrite the function batch_rename() like this maybe effectual:
def batch_rename(work_dir,old_part,new_part):
	for filename in os.listdir(work_dir):
		if filename.find(old_part) != -1:
			print filename
			newname = filename.replace(old_part,new_part)
			os.rename(
				os.path.join(work_dir,filename),
				os.path.join(work_dir,newname)
				)
e.g:cmd >python batch_file_rename.py work_dir img my_neat_event_20151231_
