### ISSUE TITLE
Possible empty password file

### ISSUE THREAD

**Issue by udoyen** [geekcomputers/Python#28]
I looked through your code and as a current student learning python I was asked to pick any code and see if I can correct any errors. 

Well I would think adding an **"else"** statement to the main function would help in **preventing  the processing** of empty password files by the users.

**Comment by diyeshsangani** [comment]
Thanks.. I debugged it long ago, but forgot to update the code. Anyways..
Thank you

**Comment by udoyen** [comment]
Thanks for your response. I will close the issue now.
