### ISSUE TITLE
TicTacToe.py inputs aren't working

### ISSUE THREAD

**Issue by thejuice2e2** [geekcomputers/Python#312]
The player inputs for function inputPlayerLetter(), playAgain(), and getPlayerMove() aren't being recognized and working.  I changed it from input to raw_input and the game is working as expected.  I know the raw_input should be used for strings which makes since why input didn't work for inputPlayerLetter() and getPlayerMove(), but it doesn't make sense why input doesn't work getPlayerMove().

**Comment by bertokhoury** [comment]
I simply think raw_input versus input is a matter of Python versions (input being python 3) (raw_input being Python 2)

**Comment by christianbender** [comment]
Yes. I tried it with Python 2, I got an error. With Python 3 it works fine.
