### ISSUE TITLE
how can I  to use the function of pop()?

### ISSUE THREAD

**Issue by wxde** [geekcomputers/Python#313]
example as follow:
          i would like to pop a one value of a list and reture the value to another variable.
 such as:
         value_a = img.pop()
         however the error is value_a is a nonetype.
         so how can I to deal with this problem?

**Comment by mrchaosbude** [comment]
li= [1,2,3]

po =li.pop()
print (li, po) 


For me this workers

**Comment by wxde** [comment]
thanks , yeap, but i want to pop the first data of li.
such as po =li.pop(0) ,this dosen't work




发自网易邮箱大师
On 3/22/2018 17:38，Maik Thunack<notifications@github.com> wrote：

li= [1,2,3]

po =li.pop()
print (li, po)

For me this workers

**Comment by mrchaosbude** [comment]
https://repl.it/repls/YellowgreenRecursiveQueryoptimizer

Workers too

**Comment by Naman-Garg-06** [comment]
If you just want to pop first element of the list, use li.pop(0) 
This gives the correct result.
You can check it on the link prvoided below:
https://repl.it/repls/GrayWindySpool

**Comment by wxde** [comment]
thanks,it works in your link address.
发自网易邮箱大师
On 3/23/2018 23:00，Naman Kumar Garg<notifications@github.com> wrote：

If you just want to pop first element of the list, use li.pop(0)
This gives the correct result.
You can check it on the link prvoided below:
https://repl.it/repls/GrayWindySpool

**Comment by faresbessrour** [comment]
@geekcomputers This can be closed

**Comment by Aakash456** [comment]
The method pop() removes and returns last object or obj from the list.

Syntax
Following is the syntax for pop() method −

list.pop(obj = list[-1])
Parameters
obj − This is an optional parameter, index of the object to be removed from the list.

Return Value
This method returns the removed object from the list.

Example
The following example shows the usage of pop() method.

#!/usr/bin/python

aList = [123, 'xyz', 'zara', 'abc'];
print "A List : ", aList.pop()
print "B List : ", aList.pop(2)
When we run above program, it produces following result −

A List :  abc
B List :  zara

**Comment by cclauss** [comment]
@wxde Can you please close this issue?
