### ISSUE TITLE
how to use XOR

### ISSUE THREAD

**Issue by cxm1995** [geekcomputers/Python#316]
ues xor

**Comment by beebus** [comment]
I assume that you mean that instructions of how to use the XOR cypher need to documented somewhere.

**Comment by christianbender** [comment]
@cxm1995  I wrote the XOR cipher.  
You can simply type:  
```python
c = XORCipher() # default key = 0
print c.encrypt("hello world", <key>) # => prints the encrypted message of "hello world"
# for <key> you can given an integer. 
```

You use the help-function. For instance ```help(XORCipher)``` gets you all informations. Or ```help(XORCipher.encrypt)``` all informations about the enrypt() method.

**Comment by cclauss** [comment]
@cxm1995 Can you please submit a pullequest or close this issue?
