### ISSUE TITLE
Google_News .py

### ISSUE THREAD

**Issue by shadedKE** [geekcomputers/Python#329]
Google_News.py not working due to the following code 
 ```

	s_url ="https://news.google.com/news/headlines/section/topic/SPORTS.en_in/Sports?ned=in&hl=en-IN&gl=IN"
	Client=urlopen(s_url)
```
This code is not parsed by 
```
        xml_page=Client.read()
	Client.close()

	soup_page=soup(xml_page,"xml")
	news_list=soup_page.findAll("item")
```
Due to the fact that there is no xml found in that url.

**Comment by mohitsharmaaa** [comment]
Thanks for notifying issue.

Problem is resolved till this get merged you can find new code  [here](https://github.com/mohitsharmaaa/Python/blob/master/Google_News.py)

XML parser was not added initially I have added it now.
URL issue is also resolved.
