### ISSUE TITLE
dict unpacking

### ISSUE THREAD

**Issue by rbk1379** [geekcomputers/Python#349]
d = {'a':1,'b':2,'c':3}
for key,value in d.items:
    print(value)

TypeError                                 Traceback (most recent call last)
<ipython-input-51-8d57fe0bffcc> in <module>()
----> 1 for key,value in d.items:
      2     print(value)

TypeError: 'builtin_function_or_method' object is not iterable

**Comment by Siddharth-Vadapalli** [comment]
To print values, use inbuilt values() method of dict.
for value in d.values():
----print(value)

**Comment by weiyd** [comment]
d = {'a':1,'b':2,'c':3}
for key,value in d.items():
    print(value)

**Comment by weiyd** [comment]
d = {'a':1,'b':2,'c':3}
for key,value in d.items():
----print(value)

**Comment by salas182** [comment]
Seems to have just forgotten the () after d.items():

**Comment by gauravguptagg** [comment]
Just use a () after **_items_** in the 2nd line of your code.
Or just print values of your dictionary using the in-build method called **_values()_**

`for value in d.values():
    print value`

**Comment by LeelKumar** [comment]
d = {'a':1,'b':2,'c':3}

[value for value in d.values()]

**Comment by cclauss** [comment]
Can this issue be closed?
