### ISSUE TITLE
osinfo.py simplification

### ISSUE THREAD

**Issue by dmahugh** [geekcomputers/Python#37]
FYI, you can use enumerate() to simplify osinfo.py. Instead of this:

`i=1`
`for item in profile:`
`print( '#',i,' ',item)`
`i=i+1;`

... do this ...

`for i, item in enumerate(profile, 1):`
`print( '#',i,' ',item)`

**Comment by geekcomputers** [comment]
Thanks, feel free to make the change

Cheers
Craig

**Comment by dmahugh** [comment]
Pull request submitted. Nice set of tools, I'll continue looking through them. Cheers.

**Comment by geekcomputers** [comment]
Thanks very much
