### ISSUE TITLE
What kind of programs can we submit to the repo?

### ISSUE THREAD

**Issue by vinay-deshmukh** [geekcomputers/Python#431]
I'm seeing a lot of programs here, and was hoping to contribute some code, but I'm not sure what exactly is the criteria for pushing files to this repository.

If possible, can you add a CONTRIBUTING.MD as a guide for others who may want to contribute?

**Comment by geekcomputers** [comment]
Nice and simple really, write your code and submit it, no real criteria if you think it can help others then push it up here

Cheers

**Comment by jinyoungHan** [comment]
I think it's a very good policy.

**Comment by cclauss** [comment]
@vinay-deshmukh Can this issue be closed?

**Comment by vinay-deshmukh** [comment]
Sure

> @vinay-deshmukh Can this issue be closed?
