### ISSUE TITLE
measure_time(Timer) for a process

### ISSUE THREAD

**Issue by Safaamahrach** [geekcomputers/Python#517]
salam'
Please I want create a Timer (with start, stop, reset functions) for that  I use the following program
[Timer.txt](https://github.com/geekcomputers/Python/files/3465429/Timer.txt)

and I make a simple example to call the timer program for timing a process
[call_Timer.txt](https://github.com/geekcomputers/Python/files/3465433/call_Timer.txt)

I always get the next result (None)
![image](https://user-images.githubusercontent.com/31244674/62430709-f8559580-b717-11e9-80fc-3395c94bbf2a.png)

Please I want to know what is the problem

**Comment by Rapheal-Jones** [comment]
in start and stop function you have to return to get the values in function call
[Timer.txt](https://github.com/geekcomputers/Python/files/3485372/Timer.txt)

**Comment by Safaamahrach** [comment]
it s ok thank you
