### ISSUE TITLE
Hacktoberfest: Python 3 compatibility issues

### ISSUE THREAD

**Issue by cclauss** [geekcomputers/Python#552]
91 days until Python 2 end of life.  https://www.python.org/doc/sunset-python-2

[flake8](http://flake8.pycqa.org) testing of https://github.com/geekcomputers/Python on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./movie_details.py:14:15: F821 undefined name 'raw_input'
movie_title = raw_input("Enter movie title: ")
              ^
./pan.py:159:8: E999 SyntaxError: invalid syntax
print df.ix[:,'A']
       ^
./internet_connection_py3.py:12:16: F821 undefined name 'raw_input'
    question = raw_input("Do you want to open a website? (Y/N): ")
               ^
./internet_connection_py3.py:15:15: F821 undefined name 'raw_input'
    	search = raw_input("Input website to open (http://website.com) : ")
              ^
./WikipediaModule.py:15:10: F821 undefined name 'raw_input'
    word=raw_input("Wikipedia Search : ")
         ^
./Guess_the_number_game.py:37:34: F821 undefined name 'range1000'
frame.add_button("range[0-1000)",range1000)
                                 ^
./Guess_the_number_game.py:38:33: F821 undefined name 'range100'
frame.add_button("range[0-100)",range100)
                                ^
./sendemail.py:42:20: F821 undefined name 'createMessageWithAttachment'
        message1 = createMessageWithAttachment(sender, to, subject, msgHtml, msgPlain, attachmentFile)
                   ^
1     E999 SyntaxError: invalid syntax
7     F821 undefined name 'range1000'
8
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by laurent-pck** [comment]
The above PR fixes all but one error given by flake8. In sendemail.py there is commented code. I don't know if it would be better to remove it or to let it uncommented.

**Comment by cclauss** [comment]
See #587
