### ISSUE TITLE
There are some problems in Python/Counting-sort.py

### ISSUE THREAD

**Issue by WHYBBE** [geekcomputers/Python#572]
If you enter a float to element, this program would return a ValueError because of invalid literal for int(). This is ok. It can be fixed by adding error judge. 
But if you enter a negative number to element, there would not have a error warning. It causes by Python‘s special grammar.
```Python
l = [1,2,3,4,5]
print(l[-4])
```
The result will be 2. So I think there should add some ways to avoid this situation.
I am poor in English. I hope you understand.

**Comment by CodeGuro** [comment]
@WHYBBE Python indexes can be a negative number as per the language. Negative indexes are offsets from len(list)-index, so an index of -1 gives you the last element, an index of -2 gives you the 2nd last element, etc...
