### ISSUE TITLE
error in youtube.py

### ISSUE THREAD

**Issue by hanzohasashi33** [geekcomputers/Python#663]
i'm getting the same youtube video irrespective of whatever i search in input song.
please can you look into this issue?

regards

**Comment by Yorozuya-san** [comment]
I could not find any issue with it.
Could you please elaborate

**Comment by saurabh896** [comment]
Can you share the code?

**Comment by hanzohasashi33** [comment]
Sorry, I figured it on my own.
Thanks for the support anyways
