### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by UnstoppableGeek1** [geekcomputers/Python#733]
I am trying to make a program that has me input multiple numbers into the console (specifically in Pythonista) and will then  add all of the numbers together and give back the sum.

This is the code I have so far
I am trying to make it only accept numbers if it knows it is a number and if it is a string it will say that it is not a number but i am stuck on how to get it to recognize an integer from a string. 

Some help on how to get it to add however many numbers i put into the console would be helpful to. I think i will have to use either *args, or **kwargs but i am not sure how to do it or if there is a better way to do it. 

Any help would be appreciate 

numbers = int()
while True:
	numbers = input("Enter some numbers: ")
	try:
		if str(numbers):
			print(numbers, "is not a number")
	except:
		pass

**Comment by MusafirRahi123** [comment]
Try this
numbers = int()
while True:
    numbers = input("Enter some numbers: ")
    if(numbers.isnumeric() == False):
        print("Error")
        break

**Comment by MaksHub-coder** [comment]
Check this out :) 
number1 = input("Enter a number (Use space between each number): ")
number2 = number1.split()
map_object = map(int,number2)
no = list(map_object)
print(no)
print("The sum of all integers inside the List",sum(no))

**Comment by Akshima-Ghai** [comment]
num1=int(input('enter first number'))
num2=int(input('enter second number '))

that's it , it will only accept integers , otherwise throws an error

**Comment by ndmichael** [comment]
Depends on what you intend to do.
You can use a flag and take multiple values on seperate lines like this.

terminate = False
listt = []
result = None
print("enter multiple numbers to be added, press an empty space to end")
while not terminate:
  try:
    user_input = int(input())
    if user_input == ' ':
      terminate = True
    else:
      listt.append(user_input)

  except:
    terminate=False
else:
  result = sum(listt)

print(f"the sum of all your values are {result})

Note: that the final else is for the while loop.

Another way is allow put in multiple values at a time.
try:
  user_input = int(input("enter your numbers")).split(" ")
except(ValueError, TypeError):
  print('enter value in a single line')
  Raise ValueError
else:
  result = sum(user_input)
  print(result)

 If you want to use function you can take the user_input variable and pass
directly to fuction to evaluate.
Note: that i have not testrun the code#
#HopeThisHelps

**Comment by Moshiurmilton** [comment]
# I have made a solution.
while True:
    user_input = input("Enter number (Use + between each number): ")
    user_input = user_input.split("+")
    try:
        map_object = map(int, user_input)
        lst = list(map_object)
        print("The sum of the numbers =", sum(lst))
    except(ValueError, TypeError):
        print("SyntaxError")
