### ISSUE TITLE
I can’t get the sub function to subtract any numbers properly

### ISSUE THREAD

**Issue by UnstoppableGeek1** [geekcomputers/Python#738]
def sub(list):
	sub = 0
	for i in list:
		sub -= i
	return sub 		

while True:
	number1 = input("Enter a number (Use space between each number): ")
	number2 = number1.split()
	print(number2)
	map_object = map(int, number2)	
	no = list(map_object)
	print(no)
	print("The sum of all integers inside the list is: ",sum(no))
	print("The sub of all interers inside the list is: ",sub(no))

The sub function is not subtracting the numbers I enter in the console

Does anyone have any suggestions on how to get this to work?

**Comment by Moshiurmilton** [comment]
Your program's output: and its pretty good. What's wrong I can not understand.
Enter a number (Use space between each number): 25 69 64 68
['25', '69', '64', '68']
[25, 69, 64, 68]
The sum of all integers inside the list is:  226
The sub of all integers inside the list is:  -226
Enter a number (Use space between each number):

**Comment by UnstoppableGeek1** [comment]
The subtraction function does not work properly. It will not subtract the numbers. It just says the opposite of the sum

**Comment by Moshiurmilton** [comment]
Try with this code bellow. It will substract 2nd from 1st, substact 3rd number from past result and so on.

def sub(list):
    sub = list[0]
    for i in range(1, len(list)):
        print(list[i])
        sub = sub - list[i]
    return sub

**Comment by Moshiurmilton** [comment]
print(list[i]) is not necessary. Delete this from 4th line please.

**Comment by UnstoppableGeek1** [comment]
Ok thank you
