### ISSUE TITLE
Can’t get it to ignore the space when counting a string

### ISSUE THREAD

**Issue by UnstoppableGeek1** [geekcomputers/Python#740]
I am unable to get this to ignore a space so if I typed “hello world” it would say that there are 11 letters in this string instead of 10 letters because it counted the space. Does anyone have any ideas on how to get it to ignore the space?

Here is the code:

def leng(string):
	count = 0
	for i in string:
		count += 1
	return count 

word = ""

while True:
	word = input("Enter a string: ")
	
	try:
		int(word)
		print(word, "is not a string")
		break # makes it end the while loop if it goes through try.
	except:
		print(word)
		print("There are", leng(word), "letters in", word)

**Comment by Moshiurmilton** [comment]
Done:
def leng(strng):
    l = list(strng)
    try:
        l.remove(' ')
    except:
        pass
#     count = 0
#     for i in string:
#         count += 1
    return len(l)
#
word = ""

while True:
    word = input("Enter a string: ")

    try:
        int(word)
        print(word, "is not a string")
        break # makes it end the while loop if it goes through try.
    except:
        print(word)
        print("There are", leng(word), "letters in", word)

**Comment by UnstoppableGeek1** [comment]
Thank you

**Comment by makcmoscow** [comment]
your_string = your_string.replace(' ', '')

пн, 25 мая 2020 г. в 04:13, UnstoppableGeek1 <notifications@github.com>:

**Comment by Swastik-Saha** [comment]
# Use this function

def leng(word):
    word = word.replace(' ', '')
    return len(word)
