### ISSUE TITLE
Wondering what MacBook Pro is best for coding

### ISSUE THREAD

**Issue by UnstoppableGeek1** [geekcomputers/Python#743]
I was wondering what MacBook and specifications someone would recommend for coding. I am not completely sure what kind of coding I want to do because I am just getting into it but I was thinking about app development in Xcode or even web design. I saw that Apple had a 2019 MacBook Pro 13 inch 2.4ghz model refurbished on their website but was unsure if I should get that or if I should get a different MacBook Pro. My budget is about $1500 if that helps at all. If anyone could help me out it would be greatly appreciated.

**Comment by kerwin6182828** [comment]
MacBook Pro 13 inch  2020 basic configuration will be good

**Comment by UnstoppableGeek1** [comment]
Do you think the 2019 MacBook Pro 13 inch would work to? It has 8GB of ram 256GB of storage and has a quad core i5 2.4ghz processors with 4 thunderbolt 3 ports and 2 fans. I know it has the butterfly keyboard but I haven’t heard about anyone having issues with the keyboard and it is also covered under the keyboard replacement program.
