### ISSUE TITLE
How can I search through a list using input

### ISSUE THREAD

**Issue by UnstoppableGeek1** [geekcomputers/Python#746]
I am trying to complete this login project but I am not sure how to search a list for something I entered into the input command. As you can see I am trying to see if what was typed for username_input is in the usernames list but it does not work. it instead jumps to the else statement that says "There is no username" + username_Input. 

Note this is after I created an account because I am not sure how to save things permanently in a folder or something so I could just run the program type login and enter the information without having to create an account every time even though I made the same account every other time I tried to run the program. 

Any help would be appreciated. 

Here is my code so far:

usernames = []
passwords = []

while True:
    user_Input = input("Enter login, create account, or exit: ")
    if user_Input == "login":
        username_Input = input("Enter you username: ")
        if username_Input == usernames:
            password_Input = input("Enter your password: ")
            if password_Input == passwords:
                print("You have successfully loged in " + name + ".")
            else:
                print("That is the wrong password!")
        else: 
            print("There is no username " + username_Input + ".")

    elif user_Input == "create account":
        create_username = input("Enter a new username: ")
        if create_username == usernames:
            print("That username already exists.")
        else:
            usernames.append(create_username)
            print("Username saved")
            create_password = input("Enter a password: ")
            renter_password = input("Renter the password: ")
            if create_password == renter_password:
                passwords.append(renter_password)
                print("Password has been saved")
            else:
                print("These passwords don't match. Try again")
                reenter_password
    elif user_Input == "exit":
        print("Goodbye")
        break
    elif user_Input == "Print username list":
        print("Usernames")
        print(usernames)

**Comment by yashu762001** [comment]
I will try to resolve the issue

**Comment by yashu762001** [comment]
For searching just use .index function that is in your code just add 1 extra line :
if(usernames.index('user_input')>=0):
            password_Input = input("Enter your password: ")
            if passwords.index(password_input)>=0:
                         print("You have successfully logged in " + name + ".")

**Comment by Aniketks29** [comment]
For searching an element in a list just use this(Use "in" method for searching any element in a list in python) -
if user_input in usernames:
    password_Input = input("Enter your password:  ")
    if password_Input in passwords:
        print("You have successfully logged in " + name + ".")
    else:
        print("You have entered wrong password! Please retry again")
else:
    print("The username you entered does not exist.")

**Comment by UnstoppableGeek1** [comment]
Thanks
