### ISSUE TITLE
Trying to delete a key from a dictionary 

### ISSUE THREAD

**Issue by UnstoppableGeek1** [geekcomputers/Python#748]
When the user types in forgot password it runs fine until it gets to del logins[current_password].
Here I am trying to delete the key of that value in the logins dictionary and then reassign the new username to the value current_password. When I run this it makes the new key but it doesn't delete the old key which was the whole point of writing the del logins[current_password] command. Does anyone know how to remove the old key using the value associated with the key?
By typing logins into the command prompt it will return what is in the dictionary but you have to create an account first so it can add it to the dictionary. It is the last elif statement that does this. 

Here is my code:

# Problem
# There is no forgot username or password command

usernames = []
passwords = []
logins = dict(zip(usernames, passwords))

while True:
    user_Input = input("Enter login, create account, forgot username, forgot password, or exit: ")
    if user_Input.lower() == "Login".lower():
        while True:
            username_Input = input("Enter you username or type exit: ")
            if username_Input.lower() == "Exit".lower():
                print(" ")
                break
            elif username_Input not in logins.keys(): 
                print("There is no username " + username_Input + ".")
                print(" ")
                continue
            # Could have done/ elif usernames.index(username_Input)>=0:
            elif username_Input in logins.keys():
                print(" ")
                while True:
                    password_Input = input("Enter your password: ")   
                    if password_Input in logins.values() and logins[username_Input] == password_Input:
                        print("You have successfully loged in " + username_Input + ".") 
                        print(" ")
                        break       
                    elif password_Input not in logins.values() or logins[username_Input] != password_Input:
                        print("That is the wrong password! Try Again")
                        print(" ")
                        continue
            break
        

    elif user_Input.lower() == "Create Account".lower():
        while True:
            create_username = input("Enter a new username or type exit: ")
            if create_username.lower() == "exit".lower():
                print(" ")
                break
            elif create_username in logins:
                print("That username already exists.")
                print(" ")
                continue
            elif create_username not in logins:
                print(" ")
                while True:
                    create_password = input("Enter a password: ")
                    renter_password = input("Renter the password: ")
                    if create_password == renter_password:
                        logins[create_username] = renter_password
                        print("Your username and password saved.")
                        print(" ")
                        break
                    else:
                        print("These passwords don't match. Try again")
                        print(" ")
                        continue
            break
    
    elif user_Input.lower() == "Forgot Username".lower():
        while True:
            current_password = input("Enter your current password or type exit: ")
            if current_password.lower() == "exit".lower():
                    print(" ")
                    break
            elif current_password in logins.values():
                create_username = input("Enter your new username or type exit: ")
                if create_username.lower() == "exit".lower():
                    print(" ")
                    break
                elif create_username in logins:
                    print("That username already exists.")
                    print(" ")
                    continue
                elif create_username not in logins:
                    del logins[current_password]
                    logins[create_username] = current_password
                    print("Username has been reset.")
                    print(" ")
                    break
            else:
                print("That password is incorrect. Try again")
                continue
            

    elif user_Input.lower() == "exit".lower():
        print("Are you sure you want to exit?")
        sure_Input = input("Type Yes or No: ")
        if sure_Input.lower() == "Yes".lower():
            print("Goodbye")
            print(" ")
            break
        elif sure_Input.lower() == "No".lower():
            print(" ")
            continue
    elif user_Input.lower() == "logins".lower():
        print(logins)
        
    else:
        print("TRY AGAIN!")
        print(" ")
        continue

**Comment by dummyVariable** [comment]
You cant delete a dictionary item by its value(current_password), you have to pass by its key(current_username)
Try this
```python
def getUserByPassword(password):
	for key,value in logins.items():
		if value == password:
			return key    
	return False

current_username = getUserByPassword(current_password)
del logins[current_username]
```
P.S. I don't think its ideal to edit user by asking one's password.
