### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by aeco00** [geekcomputers/Python#8]
it says,
ImportError no module named crypt:

**Comment by aeco00** [comment]
#update
i fixed this issue by using fcrypt modlue ( it is same as crypt, written for windows, as crypt don't work on windows)
but,now it is saying ->
.
no such file or directory 'passwords.txt'
.
.
(sorry i am new to programming, and i am starting with pyhon as my first language..i admit i know a little)

**Comment by geekcomputers** [comment]
Apologies for the delay, did you work this out in the end?

Regards
Craig
